version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrigest-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - agrigest

  nginx:
    image: nginx:alpine
    container_name: agrigest-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - agrigest

  db:
    image: mysql:8.0
    container_name: agrigest-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

    networks:
    
      - agrigest
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: agrigest-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - agrigest

networks:
  agrigest:
    driver: bridge

volumes:
  dbdata:
    driver: local
